In [26]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [27]:
# 读取数据集
iris = pd.read_csv('D:\XData\jupyter note\Iris\iris.csv')
iris = np.array(iris)
print(iris)
# print(list(iris.columns))

[[5.1 3.5 1.4 0.2 'Setosa']
 [4.9 3.0 1.4 0.2 'Setosa']
 [4.7 3.2 1.3 0.2 'Setosa']
 [4.6 3.1 1.5 0.2 'Setosa']
 [5.0 3.6 1.4 0.2 'Setosa']
 [5.4 3.9 1.7 0.4 'Setosa']
 [4.6 3.4 1.4 0.3 'Setosa']
 [5.0 3.4 1.5 0.2 'Setosa']
 [4.4 2.9 1.4 0.2 'Setosa']
 [4.9 3.1 1.5 0.1 'Setosa']
 [5.4 3.7 1.5 0.2 'Setosa']
 [4.8 3.4 1.6 0.2 'Setosa']
 [4.8 3.0 1.4 0.1 'Setosa']
 [4.3 3.0 1.1 0.1 'Setosa']
 [5.8 4.0 1.2 0.2 'Setosa']
 [5.7 4.4 1.5 0.4 'Setosa']
 [5.4 3.9 1.3 0.4 'Setosa']
 [5.1 3.5 1.4 0.3 'Setosa']
 [5.7 3.8 1.7 0.3 'Setosa']
 [5.1 3.8 1.5 0.3 'Setosa']
 [5.4 3.4 1.7 0.2 'Setosa']
 [5.1 3.7 1.5 0.4 'Setosa']
 [4.6 3.6 1.0 0.2 'Setosa']
 [5.1 3.3 1.7 0.5 'Setosa']
 [4.8 3.4 1.9 0.2 'Setosa']
 [5.0 3.0 1.6 0.2 'Setosa']
 [5.0 3.4 1.6 0.4 'Setosa']
 [5.2 3.5 1.5 0.2 'Setosa']
 [5.2 3.4 1.4 0.2 'Setosa']
 [4.7 3.2 1.6 0.2 'Setosa']
 [4.8 3.1 1.6 0.2 'Setosa']
 [5.4 3.4 1.5 0.4 'Setosa']
 [5.2 4.1 1.5 0.1 'Setosa']
 [5.5 4.2 1.4 0.2 'Setosa']
 [4.9 3.1 1.5 0.2 'Setosa']
 [5.0 3.2 1.2 0.2 'S

In [28]:
# 获取特征和标签
features = iris[:, :-1]
lable = iris[:, -1]
print(features)
print(lable)

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(features, lable, test_size=0.3)#, random_state=0)

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [29]:
# 计算先验概率
pri_probs = {}
# 统计每个类别的样本个数
Species_count = {}
#得到类别数据
lables = set(y_train)
print(lables)

for l in lables:
    count = 0
    for s in y_train:
        if (s == l):
            count += 1
    Species_count[l] = count
    pri_prob = count / len(y_train)
    pri_probs[l] = pri_prob
print(Species_count)
print(pri_probs)

{'Virginica', 'Versicolor', 'Setosa'}
{'Virginica': 34, 'Versicolor': 32, 'Setosa': 39}
{'Virginica': 0.3238095238095238, 'Versicolor': 0.3047619047619048, 'Setosa': 0.37142857142857144}


In [30]:
# 预测类别
def predict(test_attr, pri_probs):

    # 密度估计(使用高斯密度)
    species = ''
    maxProb = 0

    #对每个类别的特征计算条件概率，最后计算后验概率
    for l in lables:
        pos_prob = pri_probs[l]#先验概率
        count = 0
        for attr in test_attr:
            #找到对应类别的每个特征的值
            attr_list = []  # 特征值列表
            index = np.argwhere(y_train == l)  # 记录每个类别对应特征的索引
            for i in index:
                attr_list.append(x_train[i, count])

            # 计算均值
            attr_mean = np.mean(attr_list)
            # 计算方差
            attr_var = np.std(attr_list)**2
            # 计算高斯密度得到类条件密度
            Gauss = np.exp((-1) * (attr-attr_mean)**2 / (2 * attr_var)) / np.sqrt(2 * np.pi * attr_var)

            #先验概率乘条件概率
            pos_prob *= Gauss
            count += 1
        #后验概率大的对应的类别作为预测结果
        if pos_prob > maxProb:
            maxProb = pos_prob
            species = l

    return species

In [31]:
#测试结果
count = 0
for i in range(len(x_test)):
    pre = predict(x_test[i], pri_probs)
    if pre == y_test[i]:
        count += 1
    print("测试集第%d个标签为：%s，预测为：%s" % (i+1, y_test[i], pre))

print("准确率：%f" % (count/len(x_test)))

测试集第1个标签为：Versicolor，预测为：Versicolor
测试集第2个标签为：Versicolor，预测为：Versicolor
测试集第3个标签为：Virginica，预测为：Virginica
测试集第4个标签为：Virginica，预测为：Virginica
测试集第5个标签为：Versicolor，预测为：Versicolor
测试集第6个标签为：Virginica，预测为：Virginica
测试集第7个标签为：Versicolor，预测为：Versicolor
测试集第8个标签为：Versicolor，预测为：Versicolor
测试集第9个标签为：Versicolor，预测为：Versicolor
测试集第10个标签为：Versicolor，预测为：Versicolor
测试集第11个标签为：Versicolor，预测为：Virginica
测试集第12个标签为：Virginica，预测为：Virginica
测试集第13个标签为：Setosa，预测为：Setosa
测试集第14个标签为：Virginica，预测为：Virginica
测试集第15个标签为：Virginica，预测为：Virginica
测试集第16个标签为：Setosa，预测为：Setosa
测试集第17个标签为：Virginica，预测为：Virginica
测试集第18个标签为：Setosa，预测为：Setosa
测试集第19个标签为：Versicolor，预测为：Versicolor
测试集第20个标签为：Versicolor，预测为：Versicolor
测试集第21个标签为：Virginica，预测为：Virginica
测试集第22个标签为：Setosa，预测为：Setosa
测试集第23个标签为：Versicolor，预测为：Versicolor
测试集第24个标签为：Versicolor，预测为：Versicolor
测试集第25个标签为：Versicolor，预测为：Versicolor
测试集第26个标签为：Versicolor，预测为：Versicolor
测试集第27个标签为：Setosa，预测为：Setosa
测试集第28个标签为：Setosa，预测为：Setosa
测试集第29个标签为：Virginica，预测为：Virginica
测试集